FROM ruby:3.2-bookworm
RUN apt-get update -qq && apt-get install -y build-essential default-libmysqlclient-dev nodejs
RUN mkdir /calculist-web
WORKDIR /calculist-web
COPY Gemfile /calculist-web/Gemfile
RUN gem install bundler
RUN bundle install
COPY . /calculist-web
CMD ["bundle", "exec", "rspec"]
