FROM ruby:2.7.8-bullseye
RUN apt-get update -qq && apt-get install -y build-essential default-libmysqlclient-dev nodejs
RUN mkdir /calculist-web
WORKDIR /calculist-web
COPY Gemfile /calculist-web/Gemfile
COPY Gemfile.lock /calculist-web/Gemfile.lock
RUN gem install bundler -v 1.17.3
RUN bundle update rack && bundle install
COPY . /calculist-web
CMD ["bundle", "exec", "rspec"]
