# https://docs.docker.com/compose/rails
version: '3'
services:
  db:
    image: mysql
    volumes:
      - /var/mysql_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$CALCULIST_DATABASE_PASSWORD
      - MYSQL_USER=$CALCULIST_DATABASE_USER
      - MYSQL_PASSWORD=$CALCULIST_DATABASE_PASSWORD
      - MYSQL_DATABASE=$CALCULIST_DATABASE
    ports:
      - "3307:3306"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/calculist-web
    environment:
      - RAILS_ENV
      - RAILS_SERVE_STATIC_FILES
      - SECRET_KEY_BASE
      - SHARED_SECRET
      - APP_BASE_URL
      - CALCULIST_DATABASE
      - CALCULIST_DATABASE_USER
      - CALCULIST_DATABASE_PASSWORD
      - CALCULIST_MAIN_URL
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
      - MAILGUN_USERNAME
      - MAILGUN_PASSWORD
      - STRIPE_PUBLISHABLE_KEY
      - STRIPE_SECRET_KEY
      - STRIPE_PERSONAL_PLAN_ID
      - STRIPE_PRO_PLAN_ID
    ports:
      - "3000:3000"
    depends_on:
      - db
# https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion
networks:
  default:
    external:
      name: webproxy
